name: BACKUP

on:
  # schedule:
  #     - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  Backup:
    runs-on: ubuntu-latest
    name: DB Backup
    steps:
      - name: SSH Backup
        uses: zowe-actions/shared-actions/ssh-command@main
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: "echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker exec ${{ secrets.DB_CONTAINER_NAME }} mongodump -d ${{ secrets.DB_NAME }} -o /dump/$(date +'%d-%m-%Y') -u ${{ secrets.DB_USER }} -p ${{ secrets.DB_PASS }} --authenticationDatabase ${{ secrets.DB_AUTH }}"
