name: DEPLOY

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: zowe-actions/shared-actions/ssh-command@main
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.METRICS_LOCATION }}
            git pull
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose up -d --build
